# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraduationProject.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_GraduationPro(object):
    def setupUi(self, GraduationPro):
        GraduationPro.setObjectName("GraduationPro")
        GraduationPro.resize(1012, 653)
        self.centralwidget = QtWidgets.QWidget(GraduationPro)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1011, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(40, 20, 951, 591))
        self.graphicsView.setStyleSheet("border-image: url(:/newPrefix/desktop.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(270, 70, 521, 141))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.btn_history = QtWidgets.QPushButton(self.tab)
        self.btn_history.setGeometry(QtCore.QRect(290, 260, 141, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_history.setFont(font)
        self.btn_history.setObjectName("btn_history")
        self.btn_analyse_all = QtWidgets.QPushButton(self.tab)
        self.btn_analyse_all.setGeometry(QtCore.QRect(590, 260, 161, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_analyse_all.setFont(font)
        self.btn_analyse_all.setObjectName("btn_analyse_all")
        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(480, 30, 471, 561))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(110, 140, 231, 101))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_show_his_content = QtWidgets.QPushButton(self.tab_2)
        self.btn_show_his_content.setGeometry(QtCore.QRect(150, 240, 81, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_show_his_content.setFont(font)
        self.btn_show_his_content.setObjectName("btn_show_his_content")
        self.tabWidget.addTab(self.tab_2, "")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(320, 80, 431, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_search_web = QtWidgets.QPushButton(self.tab_3)
        self.btn_search_web.setGeometry(QtCore.QRect(810, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_search_web.setFont(font)
        self.btn_search_web.setObjectName("btn_search_web")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(160, 200, 731, 341))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_3, "")
        GraduationPro.setCentralWidget(self.centralwidget)
        self.actionHow_to_use_this_Programming = QtWidgets.QAction(GraduationPro)
        self.actionHow_to_use_this_Programming.setObjectName("actionHow_to_use_this_Programming")

        self.retranslateUi(GraduationPro)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GraduationPro)

    def retranslateUi(self, GraduationPro):
        _translate = QtCore.QCoreApplication.translate
        GraduationPro.setWindowTitle(_translate("GraduationPro", "上网行为分析系统"))
        self.label.setText(_translate("GraduationPro", "上网行为分析系统"))
        self.btn_history.setText(_translate("GraduationPro", "导出历史记录"))
        self.btn_analyse_all.setText(_translate("GraduationPro", "一键分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GraduationPro", "一键分析"))
        self.label_3.setText(_translate("GraduationPro", "查看浏览器历史记录"))
        self.btn_show_his_content.setText(_translate("GraduationPro", "查看"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GraduationPro", "历史记录查看"))
        self.lineEdit.setText(_translate("GraduationPro", "https://www.baidu.com"))
        self.label_2.setText(_translate("GraduationPro", "输入想查询的网页"))
        self.btn_search_web.setText(_translate("GraduationPro", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("GraduationPro", "文本处理"))
        self.actionHow_to_use_this_Programming.setText(_translate("GraduationPro", "How to use this Programming"))
import GUI.test_qrc
